version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-semana-sistemas
    ports:
      - "8083:80"
    volumes:
      - ./public:/var/www/html/public
      - ./app:/var/www/html/app
      - ./lib:/var/www/html/lib
      - ./routes:/var/www/html/routes
      - ./autoloader.php:/var/www/html/autoloader.php
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: blog-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blog_db
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
    ports:
      - "3307:3306"
    volumes:
      - blog_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpass || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: blog-phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8084:80"

volumes:
  blog_data:
